---
- name: DEPLOY GIT CONFIG
  hosts: "localhost"
  become: false
  tasks:
  - include_vars: "../vars.yaml"
  - name: Add username to .gitconfig
    git_config:
      name: user.name
      scope: global
      value: Daniel Juenger
  - name: Add email to .gitconfig
    git_config:
      name: user.email
      scope: global
      value: 2955913+sleeepyjack@users.noreply.github.com
  - name: Add default branch to .gitconfig
    git_config:
      name: init.defaultBranch
      scope: global
      value: main
  - name: Copy GPG key file
    copy:
      src: "../files/github.asc"
      dest: "/tmp/github.asc"
    changed_when: false
    no_log: true
  - name: Import GPG key
    shell:
      gpg --batch --pinentry-mode loopback --import /tmp/github.asc
    changed_when: false
    no_log: true
  - name: Delete GPG key file
    file:
      path: "/tmp/github.asc"
      state: absent
    changed_when: false
    no_log: true
  - name: Add signkey to .gitconfig
    git_config:
      name: user.signingkey
      scope: global
      value: ECB8CFD5B03AD2D2
