---
- name: SET WAKATIME API KEY
  hosts: "localhost"
  gather_facts: false
  tasks:
  - include_vars: "../vars.yaml"
  - name: Export WakaTime API key
    lineinfile:
      dest: "{{ lookup('env','HOME') }}/.bashrc"
      line: "export WAKATIME_API_KEY={{ wakatime_api_key}}"
      state: present